version: 2
models:
  - name: dapplooker__
    columns:
      - name: get_chart
        tests:
          - test_udf:
              name: test_dapplooker__get_chart_status_202
              args: >
                'a68cc6dd-1bc1-40ca-aaf8-b5155785f0b4'
              validations:
                - result:status_code = 200

